env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "prettier/@typescript-eslint"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: "./tsconfig.json"
plugins:
  - react
  - '@typescript-eslint'
  - "prettier"
rules: {
  "prettier/prettier": "error",
  "max-len": ["error", {"code": 100}],
  "prefer-promise-reject-errors": ["off"],
  "react/jsx-filename-extension": ["off"],
  "react/prop-types": ["off"],
  "no-return-assign": ["off"],
  "import/no-unresolved": "off",
  "react/destructuring-assignment": "off", # propsの分割代入,
  "@typescript-eslint/ban-types": "off",
  # StoryBookで@storybook/*のdevDependenciesに関するパッケージをimport時にエラーを出さないようにする
  "import/no-extraneous-dependencies": ['error', {
    devDependencies: true, #
    optionalDependencies: false,
    peerDependencies: false,
  }],
  'react/jsx-one-expression-per-line': 'off',
  "react/jsx-props-no-spreading": "off",
  "import/prefer-default-export": "off",
  # debug
  "@typescript-eslint/no-unused-vars": "off",
  "import/extensions": ["error", "ignorePackages", {
    "js": "never",
    "jsx": "never",
    "ts": "never",
    "tsx": "never",
    "mjs": "never",
    "": "never"
  }],
  "@typescript-eslint/ban-ts-comment": "off"
}
